version: '3.8'

services:
  torrent-server:
    build:
      context: ./torrent-server
    ports:
      - "6881:6881"  # Torrent port
      - "6969:6969"  # Tracker port
    volumes:
      - ./torrent-server/video_test:/app/video_test
    networks:
      - hypertube-network

  torrent-downloader:
    build:
      context: ./torrent-downloader
    volumes:
      - ./torrent-downloader:/app
    working_dir: /app
    command: ["python3", "libtorrent_test.py"]
    networks:
      - hypertube-network

networks:
  hypertube-network:
    driver: bridge